# FlappyBird AI Configuration File

# Game Configuration
game:
  fps: 30
  window:
    width: 288
    height: 512
  physics:
    gravity: 0.5
    flap_velocity: -9
    max_velocity: 10
  pipe:
    gap: 100
    speed: 4
    spawn_distance: 200

# Training Configuration
training:
  episodes: 100000
  checkpoint_frequency: 3000
  log_frequency: 100
  early_stopping:
    enabled: true
    patience: 5000
    min_improvement: 0.01
  
  # Single Environment Training
  single:
    enabled: true
    max_steps_per_episode: 10000
  
  # Parallel Training
  parallel:
    enabled: true
    num_envs: 6
    max_steps_per_episode: 10000

# Model Configuration
model:
  architecture:
    input_dim: 5
    hidden_dims: [64, 64]
    output_dim: 2
    activation: "relu"
    dropout: 0.0
  
  # DQN Hyperparameters
  hyperparameters:
    learning_rate: 0.001
    batch_size: 64
    gamma: 0.99  # Discount factor
    epsilon:
      start: 1.0
      end: 0.01
      decay: 0.995
    memory:
      capacity: 10000
      prioritized: false  # Use prioritized experience replay
    target_update_frequency: 1000  # Steps between target network updates

# Hardware Configuration
hardware:
  device: "auto"  # auto, cpu, cuda, mps
  num_workers: 4
  pin_memory: true
  mixed_precision: false

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console:
    enabled: true
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "logs/training.log"
    max_bytes: 10485760  # 10MB
    backup_count: 5
  tensorboard:
    enabled: true
    log_dir: "tensorboard_logs/"
    flush_secs: 30
  wandb:
    enabled: false
    project: "flappybird-ai"
    entity: null
    tags: ["dqn", "flappy-bird"]

# Paths
paths:
  models: "model/"
  checkpoints: "checkpoints/"
  logs: "logs/"
  assets: "assets/"
  configs: "configs/"

# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false

# Development
development:
  debug: false
  profile: false
  verbose: false
  assertions: true
